// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo1tACBX4tWSzTh6ILzrgZyX9N-k-DuiM',
    appId: '1:587474540592:web:8894bc4b20a150e05f35f5',
    messagingSenderId: '587474540592',
    projectId: 'beast-bc187',
    authDomain: 'beast-bc187.firebaseapp.com',
    storageBucket: 'beast-bc187.appspot.com',
    measurementId: 'G-QQX1LP0Y85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpfCclkcTygo4ttplJzF3qKaBNKkOZdA8',
    appId: '1:587474540592:android:cfed868595a153275f35f5',
    messagingSenderId: '587474540592',
    projectId: 'beast-bc187',
    storageBucket: 'beast-bc187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9crC5WaBh8EVEg5VeylKM3zIu3rPl8c',
    appId: '1:587474540592:ios:5aa4a2eb4f9da6cc5f35f5',
    messagingSenderId: '587474540592',
    projectId: 'beast-bc187',
    storageBucket: 'beast-bc187.appspot.com',
    androidClientId: '587474540592-ueks7loj457e9c27sas6jvc41f890209.apps.googleusercontent.com',
    iosClientId: '587474540592-9s9nhe52srhaj5bqglf2aur4121350ak.apps.googleusercontent.com',
    iosBundleId: 'com.example.meraapp',
  );
}
